# version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - mynetwork

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

# docker-compose.yml